name: Laravel Deploy to CPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, curl, dom, fileinfo, json, libxml, openssl, pdo, tokenizer, xml, ctype, zip
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
        coverage: none

    - name: Validate Composer
      run: composer validate

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Build Frontend Assets
      run: |
        npm install
        npm run build

    # Example of deploying to a remote server over SSH (you can replace with your own method)
    # - name: Deploy via SCP
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.CPANEL_HOST }}
    #     username: ${{ secrets.CPANEL_USER }}
    #     password: ${{ secrets.CPANEL_PASS }}
    #     source: "."
    #     target: "/home/youruser/public_html"
