name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml, curl
        coverage: none

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install NPM dependencies and build assets
      run: |
        npm install
        npm run build

    - name: Copy files to server via rsync over SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H testapp.cybercraftit.com >> ~/.ssh/known_hosts

        rsync -avz --delete \
          --exclude=".git*" \
          --exclude="node_modules" \
          --exclude="tests" \
          --exclude="storage/logs" \
          ./ cybercra@testapp.cybercraftit.com:/home/cybercra/repositories/Agroptix-System

    - name: Run post-deploy Laravel commands on server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh cybercra@testapp.cybercraftit.com << 'EOF'
        cd /home/cybercra/repositories/Agroptix-System
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        chmod -R 775 storage bootstrap/cache
        chown -R www-data:www-data .
        EOF
